# Generated by Django 4.2.3 on 2024-06-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
